frontend:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - '*.md'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

config:
  - changed-files:
    - any-glob-to-any-file:
      - '*.config.*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
